export const H1 = 'scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl'
export const H2 = 'scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight first:mt-0'
export const H3 = 'scroll-m-20 text-2xl font-semibold tracking-tight'
export const H4 = 'scroll-m-20 text-xl font-semibold tracking-tight'
export const P = 'leading-7 [&:not(:first-child)]:mt-6'
export const Blockquote = 'mt-6 border-l-2 pl-6 italic'
export const Table = 'w-full'
export const Th = 'border px-4 py-2 text-left font-bold [&[align=center]]:text-center [&[align=right]]:text-right'
export const Td = 'border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right'
export const List = 'my-6 ml-6 list-disc [&>li]:mt-2'
export const InlineCode = 'relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-sm font-semibold'
export const Lead = 'text-xl text-muted-foreground'
export const Large = 'text-lg font-semibold'
export const Small = 'text-sm font-medium leading-none'
export const Muted = 'text-sm text-muted-foreground'
