export const H1 = 'scroll-m-20 fd-cond text-2xl font-bold'
export const H2 = 'scroll-m-20 fd-cond border-b pb-1 text-xl font-bold first:mt-0'
export const H3 = 'scroll-m-20 fd-cond text-lg font-bold'
export const H4 = 'scroll-m-20 fd-cond text-base font-bold'
export const P = 'leading-relaxed not-first:mt-3'
export const Blockquote = 'mt-6 border-l-2 pl-6 italic'
export const Table = 'w-full'
export const Th = 'border px-4 py-2 text-left font-bold [[align=center]]:text-center [[align=right]]:text-right'
export const Td = 'border px-4 py-2 text-left [[align=center]]:text-center [[align=right]]:text-right'
export const List = 'my-3 ml-5 list-disc [&>li]:mt-1'
export const InlineCode = 'relative rounded-sm bg-ground px-1 py-px font-mono text-xs'
export const Link = 'text-[#f0b660] underline decoration-[#f0b66073] underline-offset-2 hover:text-[#ffd08a] hover:decoration-current'
export const Lead = 'text-base text-text-2'
export const Large = 'text-base font-semibold'
export const Small = 'text-sm font-medium leading-none'
export const Muted = 'text-sm text-muted-foreground'
export const Label = 'fd-lbl-k leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70'

export const LayerText = 'text-sm'

export const ConstraintViolationDescriptor = 'underline decoration-repeat-violation decoration-2'
