CREATE TABLE `serverEvents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`type` enum('NEW_GAME','ROUND_ENDED','PLAYER_CONNECTED','PLAYER_DISCONNECTED','SQUAD_CREATED','CHAT_MESSAGE','ADMIN_BROADCAST','POSSESSED_ADMIN_CAMERA','UNPOSSESSED_ADMIN_CAMERA','PLAYER_KICKED','PLAYER_BANNED','PLAYER_WARNED','PLAYER_DETAILS_CHANGED','PLAYER_CHANGED_TEAM','PLAYER_LEFT_SQUAD','SQUAD_DISBANDED','PLAYER_JOINED_SQUAD','PLAYER_PROMOTED_TO_LEADER') NOT NULL,
	`time` timestamp NOT NULL,
	`matchId` int NOT NULL,
	`version` int DEFAULT 1,
	`data` json NOT NULL,
	CONSTRAINT `serverEvents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `serverEvents` ADD CONSTRAINT `serverEvents_matchId_matchHistory_id_fk` FOREIGN KEY (`matchId`) REFERENCES `matchHistory`(`id`) ON DELETE cascade ON UPDATE no action;