import type * as Schema from '$root/drizzle/schema.ts'

export * from './enums'

export type Filter = typeof Schema.filters.$inferSelect
export type NewFilter = typeof Schema.filters.$inferInsert
export type Server = typeof Schema.servers.$inferInsert
export type Session = typeof Schema.sessions.$inferSelect
export type NewSession = typeof Schema.sessions.$inferInsert
export type DiscordAccount = typeof Schema.discordAccounts.$inferSelect
export type NewDiscordAccount = typeof Schema.discordAccounts.$inferInsert
export type LinkOrigin = Schema.LinkOrigin
export type User = typeof Schema.users.$inferSelect
export type NewUser = typeof Schema.users.$inferInsert
export type LinkedSteamAccount = typeof Schema.linkedSteamAccounts.$inferSelect
export type NewLinkedSteamAccount = typeof Schema.linkedSteamAccounts.$inferInsert
export type FilterUserContributor = typeof Schema.filterUserContributors.$inferSelect
export type NewFilterUserContributor = typeof Schema.filterUserContributors.$inferInsert
export type FilterRoleContributor = typeof Schema.filterRoleContributors.$inferSelect
export type NewFilterRoleContributor = typeof Schema.filterRoleContributors.$inferInsert
export type NewServer = typeof Schema.servers.$inferInsert
export type MatchHistory = typeof Schema.matchHistory.$inferSelect
export type NewMatchHistory = typeof Schema.matchHistory.$inferInsert
export type ServerEvent = typeof Schema.serverEvents.$inferSelect
export type NewServerEvent = typeof Schema.serverEvents.$inferInsert
export type AppEvent = typeof Schema.appEvents.$inferSelect
export type NewAppEvent = typeof Schema.appEvents.$inferInsert
export type AppEventAssociation = typeof Schema.appEventAssociations.$inferSelect
export type NewAppEventAssociation = typeof Schema.appEventAssociations.$inferInsert
export type Player = typeof Schema.players.$inferSelect
export type NewPlayer = typeof Schema.players.$inferInsert
export type Timeout = typeof Schema.timeouts.$inferSelect
export type NewTimeout = typeof Schema.timeouts.$inferInsert
export type Squad = typeof Schema.squads.$inferSelect
export type NewSquad = typeof Schema.squads.$inferInsert
export type SquadEventAssociation = typeof Schema.squadEventAssociations.$inferSelect
export type NewSquadEventAssociation = typeof Schema.squadEventAssociations.$inferInsert
export type GlobalSettings = typeof Schema.globalSettings.$inferSelect
export type NewGlobalSettings = typeof Schema.globalSettings.$inferInsert
export type PluginRow = typeof Schema.plugins.$inferSelect
export type NewPluginRow = typeof Schema.plugins.$inferInsert
export type PlayerEventIndexEntry = typeof Schema.playerEventIndex.$inferSelect
export type NewPlayerEventIndexEntry = typeof Schema.playerEventIndex.$inferInsert
export type DamageSource = typeof Schema.damageSources.$inferSelect
export type NewDamageSource = typeof Schema.damageSources.$inferInsert
export type ArchivedMatch = typeof Schema.archivedMatches.$inferSelect
export type NewArchivedMatch = typeof Schema.archivedMatches.$inferInsert
export type SavedQueryRow = typeof Schema.savedQueries.$inferSelect
export type NewSavedQueryRow = typeof Schema.savedQueries.$inferInsert
export type RetainedEvent = typeof Schema.retainedEvents.$inferSelect
export type NewRetainedEvent = typeof Schema.retainedEvents.$inferInsert
