// Regenerates src/components/feed/icons.gen.ts, the lucide shapes the activity feed draws without react.
//
// The feed builds its rows as dom nodes, and an icon is a fifth of the nodes in one. Rendering each shape here,
// through lucide's own component, is what keeps the table honest: the markup is whatever lucide-react would have
// produced, so upgrading lucide and re-running this is the whole of the update.
//
//   pnpm run build:feed-icons

import * as Icons from 'lucide-react'
import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as React from 'react'
import { renderToStaticMarkup } from 'react-dom/server'

// Every icon the ported feed rows draw, app-event rows included.
const USED = [
	'AlertTriangle',
	'ArrowLeftRight',
	'Ban',
	'Camera',
	'CameraOff',
	'CheckCircle2',
	'Copy',
	'CloudFog',
	'Crown',
	'Dot',
	'Flag',
	'HeartPulse',
	'Info',
	'LogIn',
	'LogOut',
	'ListChecks',
	'ListOrdered',
	'ListPlus',
	'ListX',
	'Lock',
	'LockOpen',
	'Map',
	'Megaphone',
	'Pencil',
	'PencilLine',
	'Play',
	'Plug',
	'Puzzle',
	'Repeat',
	'RefreshCw',
	'ScrollText',
	'ShieldCheck',
	'ShieldOff',
	'Skull',
	'Star',
	'Unplug',
	'UserMinus',
	'UserPlus',
	'UserX',
	'XCircle',
	'UserCheck',
	'Users',
	'UsersRound',
	'Vote',
] as const satisfies (keyof typeof Icons)[]

const OUT = path.join(process.cwd(), 'src/components/feed/icons.gen.ts')

function shapeOf(name: string) {
	const Icon = (Icons as unknown as Record<string, React.ComponentType<Record<string, unknown>>>)[name]
	if (!Icon) throw new Error(`lucide-react has no icon named ${name}`)
	const markup = renderToStaticMarkup(React.createElement(Icon))
	const inner = /^<svg\b[^>]*>([\s\S]*)<\/svg>$/.exec(markup)
	if (!inner) throw new Error(`could not read the shape out of lucide's markup for ${name}: ${markup}`)
	const lucideClass = / class="([^"]*)"/.exec(markup)?.[1] ?? ''
	return { lucideClass, body: inner[1] }
}

const entries = USED.map((name) => {
	const { lucideClass, body } = shapeOf(name)
	return `\t${name}: ['${lucideClass}', ${JSON.stringify(body)}],`
}).join('\n')

const file = `// GENERATED by src/scripts/build-feed-icons.ts (pnpm run build:feed-icons) -- do not edit.
// Each entry is [class, inner svg markup] as lucide-react ${JSON.parse(await fs.readFile('node_modules/lucide-react/package.json', 'utf8')).version} renders it.

export const SHAPES = {
${entries}
} as const

export type IconName = keyof typeof SHAPES
`

await fs.writeFile(OUT, file)
console.log(`wrote ${USED.length} shapes to ${path.relative(process.cwd(), OUT)}`)
