import { execFileSync } from 'node:child_process'
import * as fs from 'node:fs'
import * as path from 'node:path'
import { API, type Checker, fileNameToDocumentURI, NodeBuilderFlags, type Symbol as TsSymbol, SymbolFlags } from 'typescript/unstable/sync'

import * as PLG from '@/models/plugins.models'

// Generates src/plugin-api/api-report.md: one line per export reachable through each slm/* entry,
// with values carrying their resolved signature. The report is the plugin API contract made
// explicit, and regeneration enforces semver against it:
//   - an export removed or its line changed  -> API_VERSION needs a major bump
//   - exports only added                     -> API_VERSION needs at least a minor bump
// The baseline is origin/main's copy when available, so iterating within a branch needs one bump,
// not one per regeneration. `check` fails when the checked-in report is stale.
//
// Scope: the report records which exports exist and their signatures as written. It does not expand
// the internal structure of named types, so reshaping e.g. MatchDetails without renaming it is not
// caught here; that judgement stays with review, which the report diff flags.
//
// Runs on tsgo's in-package experimental API (typescript/unstable/sync), which drives the native
// binary over IPC; the stable TS JS checker API does not exist in typescript@7.

const repoRoot = path.resolve(import.meta.dirname, '..', '..')
const apiDir = path.join(repoRoot, 'src', 'plugin-api')
const reportPath = path.join(apiDir, 'api-report.md')
const versionStr = `${PLG.API_VERSION.major}.${PLG.API_VERSION.minor}`

function entryFiles(): string[] {
	const out: string[] = []
	const walk = (dir: string) => {
		for (const name of fs.readdirSync(dir).sort()) {
			const p = path.join(dir, name)
			if (fs.statSync(p).isDirectory()) walk(p)
			else if (name.endsWith('.ts')) out.push(p)
		}
	}
	walk(apiDir)
	return out.filter((p) => !p.endsWith('api-report.md'))
}

function specifierFor(file: string): string {
	const rel = path.relative(apiDir, file).replace(/\\/g, '/').replace(/\.ts$/, '')
	return `slm/${rel}`.replace(/\/index$/, '')
}

function describeExport(checker: Checker, sym: TsSymbol): string {
	const resolved = sym.flags & SymbolFlags.Alias ? checker.getAliasedSymbol(sym) : sym
	const flags = resolved.flags
	if (flags & SymbolFlags.ValueModule || flags & SymbolFlags.NamespaceModule) {
		const members = checker
			.getExportsOfModule(resolved)
			.map((m) => m.name)
			.sort()
		return `namespace { ${members.join(', ')} }`
	}
	if (flags & SymbolFlags.Class) return `class ${resolved.name}`
	if (flags & SymbolFlags.Enum) return `enum ${resolved.name}`
	if (flags & (SymbolFlags.Interface | SymbolFlags.TypeAlias)) {
		const declared = checker.getDeclaredTypeOfSymbol(resolved)
		const params = (declared as { typeParameters?: unknown[] }).typeParameters?.length
		return `type${params ? `<${params} params>` : ''}`
	}
	const type = checker.getTypeOfSymbol(resolved)
	if (!type) return 'value'
	return `value: ${checker.typeToString(type, undefined, NodeBuilderFlags.NoTruncation)}`
}

function generateContent(): string {
	const files = entryFiles()
	const api = new API({ cwd: repoRoot })
	try {
		return generateWith(api, files)
	} finally {
		api.close()
	}
}

function generateWith(api: API, files: string[]): string {
	const snapshot = api.updateSnapshot({
		openProjects: [{ uri: fileNameToDocumentURI(path.join(repoRoot, 'tsconfig.app.json')) }],
	})
	const project = snapshot.getProjects()[0]
	const program = project.program
	const checker = project.checker
	const lines: string[] = [
		'# slm plugin API report',
		'',
		`api-version: ${versionStr}`,
		'',
		'Generated by `pnpm api:report`; checked by `pnpm api:report:check`. Do not edit by hand.',
		'One line per export reachable through each entry. A removed or changed line is a breaking',
		'change (major bump); added lines are additive (minor bump). See src/scripts/plugin-api-report.ts.',
		'',
	]
	for (const file of files) {
		const sf = program.getSourceFile(file)
		if (!sf) throw new Error(`not in program: ${file}`)
		const moduleSymbol = checker.getSymbolAtLocation(sf)
		lines.push(`## ${specifierFor(file)}`, '')
		if (moduleSymbol) {
			const exports = checker.getExportsOfModule(moduleSymbol).toSorted((a: TsSymbol, b: TsSymbol) => (a.name < b.name ? -1 : 1))
			for (const sym of exports) {
				// oxlint-disable-next-line no-useless-catch
				try {
					lines.push(`- \`${sym.name}\` — ${describeExport(checker, sym)}`)
				} catch (err) {
					throw new Error(`failed to describe ${specifierFor(file)} export ${sym.name}`, { cause: err })
				}
			}
		}
		lines.push('')
	}
	return lines.join('\n')
}

// ---- diffing & semver enforcement ----

type Parsed = { version: [number, number]; entries: Map<string, string> }

function parseReport(content: string): Parsed {
	const versionMatch = /^api-version: (\d+)\.(\d+)$/m.exec(content)
	if (!versionMatch) throw new Error('report has no api-version header')
	const entries = new Map<string, string>()
	let module = ''
	for (const line of content.split('\n')) {
		const heading = /^## (.+)$/.exec(line)
		if (heading) module = heading[1]
		const entry = /^- `([^`]+)` — (.*)$/.exec(line)
		if (entry) entries.set(`${module} :: ${entry[1]}`, entry[2])
	}
	return { version: [Number(versionMatch[1]), Number(versionMatch[2])], entries }
}

function classify(oldR: Parsed, newR: Parsed): 'none' | 'additive' | 'breaking' {
	let additive = false
	for (const [key, value] of newR.entries) {
		if (!oldR.entries.has(key)) additive = true
		else if (oldR.entries.get(key) !== value) return 'breaking'
	}
	for (const key of oldR.entries.keys()) {
		if (!newR.entries.has(key)) return 'breaking'
	}
	return additive ? 'additive' : 'none'
}

// origin/main's report is the released baseline; the disk copy covers a branch's first generation
function baseline(): string | null {
	try {
		return execFileSync('git', ['show', 'origin/main:src/plugin-api/api-report.md'], {
			cwd: repoRoot,
			encoding: 'utf8',
			stdio: ['ignore', 'pipe', 'ignore'],
		})
	} catch {
		return fs.existsSync(reportPath) ? fs.readFileSync(reportPath, 'utf8') : null
	}
}

function enforceBump(oldContent: string, newContent: string): string | null {
	const oldR = parseReport(oldContent)
	const newR = parseReport(newContent)
	const change = classify(oldR, newR)
	const [oldMajor, oldMinor] = oldR.version
	const [newMajor, newMinor] = newR.version
	if (change === 'breaking' && newMajor <= oldMajor) {
		return `the plugin API surface has BREAKING changes against ${oldMajor}.${oldMinor}: bump API_VERSION.major (src/models/plugins.models.ts)`
	}
	if (change === 'additive' && newMajor === oldMajor && newMinor <= oldMinor) {
		return `the plugin API surface has additions against ${oldMajor}.${oldMinor}: bump API_VERSION.minor (src/models/plugins.models.ts)`
	}
	return null
}

const mode = process.argv[2] ?? 'generate'
const allowNoBump = process.argv.includes('--allow-no-bump')
const content = generateContent()
const base = baseline()

if (mode === 'check') {
	const onDisk = fs.existsSync(reportPath) ? fs.readFileSync(reportPath, 'utf8') : null
	if (onDisk !== content) {
		console.error('plugin API report is stale: run `pnpm api:report` (and bump API_VERSION if it says to)')
		process.exit(1)
	}
	if (base !== null && base !== content) {
		const err = enforceBump(base, content)
		if (err) {
			console.error(err)
			process.exit(1)
		}
	}
	console.log('plugin API report is current')
} else if (mode === 'generate') {
	if (base !== null && base !== content && !allowNoBump) {
		const err = enforceBump(base, content)
		if (err) {
			console.error(err)
			console.error('(--allow-no-bump skips this, for changes to the report format itself)')
			process.exit(1)
		}
	}
	fs.writeFileSync(reportPath, content)
	console.log(`wrote ${path.relative(repoRoot, reportPath)} (api-version ${versionStr})`)
} else {
	console.error(`unknown mode: ${mode} (expected generate|check)`)
	process.exit(1)
}
