/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SandboxSandboxRouteImport } from './routes/_sandbox/sandbox'
import { Route as AppPlayersRouteImport } from './routes/_app/players'
import { Route as AppFiltersIndexRouteImport } from './routes/_app/filters/index'
import { Route as LayersLayerIdTabRouteImport } from './routes/layers.$layerId.$tab'
import { Route as AppServersServerIdRouteImport } from './routes/_app/servers.$serverId'
import { Route as AppFiltersNewRouteImport } from './routes/_app/filters/new'
import { Route as AppFiltersFilterIdRouteImport } from './routes/_app/filters/$filterId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxSandboxRoute = SandboxSandboxRouteImport.update({
  id: '/_sandbox/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPlayersRoute = AppPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFiltersIndexRoute = AppFiltersIndexRouteImport.update({
  id: '/filters/',
  path: '/filters/',
  getParentRoute: () => AppRouteRoute,
} as any)
const LayersLayerIdTabRoute = LayersLayerIdTabRouteImport.update({
  id: '/layers/$layerId/$tab',
  path: '/layers/$layerId/$tab',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServersServerIdRoute = AppServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFiltersNewRoute = AppFiltersNewRouteImport.update({
  id: '/filters/new',
  path: '/filters/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFiltersFilterIdRoute = AppFiltersFilterIdRouteImport.update({
  id: '/filters/$filterId',
  path: '/filters/$filterId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/players': typeof AppPlayersRoute
  '/sandbox': typeof SandboxSandboxRoute
  '/filters/$filterId': typeof AppFiltersFilterIdRoute
  '/filters/new': typeof AppFiltersNewRoute
  '/servers/$serverId': typeof AppServersServerIdRoute
  '/layers/$layerId/$tab': typeof LayersLayerIdTabRoute
  '/filters': typeof AppFiltersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/players': typeof AppPlayersRoute
  '/sandbox': typeof SandboxSandboxRoute
  '/filters/$filterId': typeof AppFiltersFilterIdRoute
  '/filters/new': typeof AppFiltersNewRoute
  '/servers/$serverId': typeof AppServersServerIdRoute
  '/layers/$layerId/$tab': typeof LayersLayerIdTabRoute
  '/filters': typeof AppFiltersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/players': typeof AppPlayersRoute
  '/_sandbox/sandbox': typeof SandboxSandboxRoute
  '/_app/filters/$filterId': typeof AppFiltersFilterIdRoute
  '/_app/filters/new': typeof AppFiltersNewRoute
  '/_app/servers/$serverId': typeof AppServersServerIdRoute
  '/layers/$layerId/$tab': typeof LayersLayerIdTabRoute
  '/_app/filters/': typeof AppFiltersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/players'
    | '/sandbox'
    | '/filters/$filterId'
    | '/filters/new'
    | '/servers/$serverId'
    | '/layers/$layerId/$tab'
    | '/filters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/players'
    | '/sandbox'
    | '/filters/$filterId'
    | '/filters/new'
    | '/servers/$serverId'
    | '/layers/$layerId/$tab'
    | '/filters'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/players'
    | '/_sandbox/sandbox'
    | '/_app/filters/$filterId'
    | '/_app/filters/new'
    | '/_app/servers/$serverId'
    | '/layers/$layerId/$tab'
    | '/_app/filters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SandboxSandboxRoute: typeof SandboxSandboxRoute
  LayersLayerIdTabRoute: typeof LayersLayerIdTabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sandbox/sandbox': {
      id: '/_sandbox/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/players': {
      id: '/_app/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof AppPlayersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/filters/': {
      id: '/_app/filters/'
      path: '/filters'
      fullPath: '/filters'
      preLoaderRoute: typeof AppFiltersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/layers/$layerId/$tab': {
      id: '/layers/$layerId/$tab'
      path: '/layers/$layerId/$tab'
      fullPath: '/layers/$layerId/$tab'
      preLoaderRoute: typeof LayersLayerIdTabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/servers/$serverId': {
      id: '/_app/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof AppServersServerIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/filters/new': {
      id: '/_app/filters/new'
      path: '/filters/new'
      fullPath: '/filters/new'
      preLoaderRoute: typeof AppFiltersNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/filters/$filterId': {
      id: '/_app/filters/$filterId'
      path: '/filters/$filterId'
      fullPath: '/filters/$filterId'
      preLoaderRoute: typeof AppFiltersFilterIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppPlayersRoute: typeof AppPlayersRoute
  AppFiltersFilterIdRoute: typeof AppFiltersFilterIdRoute
  AppFiltersNewRoute: typeof AppFiltersNewRoute
  AppServersServerIdRoute: typeof AppServersServerIdRoute
  AppFiltersIndexRoute: typeof AppFiltersIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppPlayersRoute: AppPlayersRoute,
  AppFiltersFilterIdRoute: AppFiltersFilterIdRoute,
  AppFiltersNewRoute: AppFiltersNewRoute,
  AppServersServerIdRoute: AppServersServerIdRoute,
  AppFiltersIndexRoute: AppFiltersIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  SandboxSandboxRoute: SandboxSandboxRoute,
  LayersLayerIdTabRoute: LayersLayerIdTabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
