/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppCommandsRouteImport } from './routes/_app/commands'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTutorialsRouteImport } from './routes/_app/tutorials'
import { Route as SandboxSandboxRouteImport } from './routes/_sandbox/sandbox'
import { Route as AppFiltersIndexRouteImport } from './routes/_app/filters/index'
import { Route as AppFiltersFilterIdRouteImport } from './routes/_app/filters/$filterId'
import { Route as AppFiltersNewRouteImport } from './routes/_app/filters/new'
import { Route as AppServersIndexRouteImport } from './routes/_app/servers.index'
import { Route as AppServersServerIdRouteImport } from './routes/_app/servers.$serverId'
import { Route as LayersLayerIdTabRouteImport } from './routes/layers.$layerId.$tab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCommandsRoute = AppCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTutorialsRoute = AppTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => AppRouteRoute,
} as any)
const SandboxSandboxRoute = SandboxSandboxRouteImport.update({
  id: '/_sandbox/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFiltersIndexRoute = AppFiltersIndexRouteImport.update({
  id: '/filters/',
  path: '/filters/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFiltersFilterIdRoute = AppFiltersFilterIdRouteImport.update({
  id: '/filters/$filterId',
  path: '/filters/$filterId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFiltersNewRoute = AppFiltersNewRouteImport.update({
  id: '/filters/new',
  path: '/filters/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServersIndexRoute = AppServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServersServerIdRoute = AppServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => AppRouteRoute,
} as any)
const LayersLayerIdTabRoute = LayersLayerIdTabRouteImport.update({
  id: '/layers/$layerId/$tab',
  path: '/layers/$layerId/$tab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AppAboutRoute
  '/commands': typeof AppCommandsRoute
  '/settings': typeof AppSettingsRoute
  '/tutorials': typeof AppTutorialsRoute
  '/sandbox': typeof SandboxSandboxRoute
  '/filters/$filterId': typeof AppFiltersFilterIdRoute
  '/filters/new': typeof AppFiltersNewRoute
  '/servers/$serverId': typeof AppServersServerIdRoute
  '/layers/$layerId/$tab': typeof LayersLayerIdTabRoute
  '/filters/': typeof AppFiltersIndexRoute
  '/servers/': typeof AppServersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AppAboutRoute
  '/commands': typeof AppCommandsRoute
  '/settings': typeof AppSettingsRoute
  '/tutorials': typeof AppTutorialsRoute
  '/sandbox': typeof SandboxSandboxRoute
  '/filters/$filterId': typeof AppFiltersFilterIdRoute
  '/filters/new': typeof AppFiltersNewRoute
  '/servers/$serverId': typeof AppServersServerIdRoute
  '/layers/$layerId/$tab': typeof LayersLayerIdTabRoute
  '/filters': typeof AppFiltersIndexRoute
  '/servers': typeof AppServersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/commands': typeof AppCommandsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tutorials': typeof AppTutorialsRoute
  '/_sandbox/sandbox': typeof SandboxSandboxRoute
  '/_app/filters/$filterId': typeof AppFiltersFilterIdRoute
  '/_app/filters/new': typeof AppFiltersNewRoute
  '/_app/servers/$serverId': typeof AppServersServerIdRoute
  '/layers/$layerId/$tab': typeof LayersLayerIdTabRoute
  '/_app/filters/': typeof AppFiltersIndexRoute
  '/_app/servers/': typeof AppServersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/commands'
    | '/settings'
    | '/tutorials'
    | '/sandbox'
    | '/filters/$filterId'
    | '/filters/new'
    | '/servers/$serverId'
    | '/layers/$layerId/$tab'
    | '/filters/'
    | '/servers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/commands'
    | '/settings'
    | '/tutorials'
    | '/sandbox'
    | '/filters/$filterId'
    | '/filters/new'
    | '/servers/$serverId'
    | '/layers/$layerId/$tab'
    | '/filters'
    | '/servers'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/about'
    | '/_app/commands'
    | '/_app/settings'
    | '/_app/tutorials'
    | '/_sandbox/sandbox'
    | '/_app/filters/$filterId'
    | '/_app/filters/new'
    | '/_app/servers/$serverId'
    | '/layers/$layerId/$tab'
    | '/_app/filters/'
    | '/_app/servers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SandboxSandboxRoute: typeof SandboxSandboxRoute
  LayersLayerIdTabRoute: typeof LayersLayerIdTabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/commands': {
      id: '/_app/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof AppCommandsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tutorials': {
      id: '/_app/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof AppTutorialsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_sandbox/sandbox': {
      id: '/_sandbox/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/filters/': {
      id: '/_app/filters/'
      path: '/filters'
      fullPath: '/filters/'
      preLoaderRoute: typeof AppFiltersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/filters/$filterId': {
      id: '/_app/filters/$filterId'
      path: '/filters/$filterId'
      fullPath: '/filters/$filterId'
      preLoaderRoute: typeof AppFiltersFilterIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/filters/new': {
      id: '/_app/filters/new'
      path: '/filters/new'
      fullPath: '/filters/new'
      preLoaderRoute: typeof AppFiltersNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/servers/': {
      id: '/_app/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof AppServersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/servers/$serverId': {
      id: '/_app/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof AppServersServerIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/layers/$layerId/$tab': {
      id: '/layers/$layerId/$tab'
      path: '/layers/$layerId/$tab'
      fullPath: '/layers/$layerId/$tab'
      preLoaderRoute: typeof LayersLayerIdTabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppCommandsRoute: typeof AppCommandsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTutorialsRoute: typeof AppTutorialsRoute
  AppFiltersFilterIdRoute: typeof AppFiltersFilterIdRoute
  AppFiltersNewRoute: typeof AppFiltersNewRoute
  AppServersServerIdRoute: typeof AppServersServerIdRoute
  AppFiltersIndexRoute: typeof AppFiltersIndexRoute
  AppServersIndexRoute: typeof AppServersIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppCommandsRoute: AppCommandsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTutorialsRoute: AppTutorialsRoute,
  AppFiltersFilterIdRoute: AppFiltersFilterIdRoute,
  AppFiltersNewRoute: AppFiltersNewRoute,
  AppServersServerIdRoute: AppServersServerIdRoute,
  AppFiltersIndexRoute: AppFiltersIndexRoute,
  AppServersIndexRoute: AppServersIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  SandboxSandboxRoute: SandboxSandboxRoute,
  LayersLayerIdTabRoute: LayersLayerIdTabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
