import * as FB from '@/models/filter-builders'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { type AppFixture, createAppFixture } from '../harness/app-fixture'
import { filter, LAYERS, queue } from '../harness/arrange'

// A repeat rule with autogen on must keep the just-played map out of autogenerated layers.
// Generation is pinned to a two-map pool, so with Gorodok freshly played the outcome is deterministic.

let app: AppFixture

beforeAll(async () => {
	app = await createAppFixture({
		layerQueue: queue(LAYERS.gorodokRaas),
		// the emulator boots on Harju, which is also in the repeat window: neither map here may collide with it
		filters: [filter('two-maps', 'Two Maps', FB.and([FB.inValues('Map', ['Gorodok', 'Skorpo'])]))],
		serverSettings: (s) => {
			s.queue.mainPool.constrainGeneration = [{ filterId: 'two-maps', applyAs: 'regular' }]
			s.queue.mainPool.repeatRules = [{ label: 'Map', field: 'Map', within: 4, autogen: true }]
		},
	})
}, 120_000)

afterAll(async () => {
	await app?.dispose()
})

function savedQueue(): { layerId?: string }[] {
	const db = app.readDb()
	try {
		const row = db.prepare(`SELECT layerQueue FROM servers WHERE id = ?`).get(app.serverId) as { layerQueue: string }
		return JSON.parse(row.layerQueue).json
	} finally {
		db.close()
	}
}

describe('repeat rules during generation', () => {
	it('never generates a map the repeat rule excludes', async () => {
		// rolling consumes the queued Gorodok layer and forces generation of the next one
		app.emu.world.endMatch()
		app.emu.world.startNewGame()

		const generated = await app.waitFor(() => {
			const q = savedQueue()
			return q.length >= 1 && q[0].layerId && q[0].layerId !== LAYERS.gorodokRaas ? q[0] : null
		}, { label: 'the generated layer', timeoutMs: 30_000 })

		// of the two maps generation may draw from, Gorodok was just played: only Skorpo remains
		expect(generated.layerId).toMatch(/^SK-/)
	})
})
